version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: glbaguni-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - glbaguni_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: glbaguni-redis-ui
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    depends_on:
      - redis
    networks:
      - glbaguni_network

volumes:
  redis_data:
    driver: local

networks:
  glbaguni_network:
    driver: bridge 